
/*<RBHead>
 *************************************************************************
 *                                                                       *
 *                      ROBERT BOSCH GMBH                                *
 *                          STUTTGART                                    *
 *                                                                       *
 *          Alle Rechte vorbehalten - All rights reserved                *
 *                                                                       *
 *************************************************************************  
 *
 *    __   __   ___  ___
 *   /_ / /  / /__  /    /__/
 *  /__/ /__/ __ / /__  /  /
 *
 *
 *************************************************************************
 *    Administrative Information (automatically filled in by eASEE)      *
 *************************************************************************
 *
 * $Filename__:BGBBAM$
 *
 * $Author____:song.zhang$
 *
 * $Function__:compensation for airflow from BKP$
 *
 *************************************************************************
 * $Domain____:$
 * $User______:song.zhang$
 * $Date______:28.11.2013$
 * $Class_____:$
 * $Name______:BGBBAM$
 * $Variant___:U1.0.1$
 * $Revision__:1$
 * $Type______:$
 * $State_____:Released$
 * $Generated_:$
 *************************************************************************
 *
 * $UniqueName:$
 * $Component_:$
 *
 *
 *************************************************************************
 * List Of Changes
 *
 * $History___:
 *
 * U1.0.1;1    28.11.2013 song.zhang
 *   Reason:change mlbr_ua to uint16
 *   Change content:change mlbr_ua to uint16
 * 
 * U1.0.1;0    22.11.2013 song.zhang
 *   change mlbr_ua to uint16
 *
 * U1.0.0;0    05.11.2013 song.zhang
 *   new
 * 
 * $
 *
 **************************************************************************
 * Administrative Information generated by ASCET
 **************************************************************************
 * Autor:              song.zhang
 * Date:               23/11/2013  16:32:42
 * Modulname:          BGBBAM
 * Implementation:     Impl
 *
 * $Generated by ASCET-SD: V5.2.2 RB-DGS 1.1
 * Expander:           Generic  CID: 521
 * Codegenerator:      ASCET-SE-RBPT V5.5.8
 * Target:    	       Generic:ME17 with class support [V5.5.8]
 * CgenOptions:
 *	Allow Double bit Size for Division Numerators=true
 *	Generate Round Operation on float to integer Assignment=false
 *	Generate Access Methods for dT (Alternative: use OS dT directly)=false
 *	Temp Vars always 32 bit (integer)=false
 *	Generate Limiters (may be changed locally)=true
 *	Protected Division=false
 *	Use SHIFT Operation on Signed Values instead of DIV Operation=true
 *	Optimize Direct Access Methods (Multiple Levels)=true
 *	Optimize Direct Access Methods (One Level)=true
 *	Add Comment with Generation Information for each Component=false
 *	Add Comment with Implementation Information for each Assignment Statement=true
 *	Add Comment with Specification Source for each Statement=true
 *	Add Implementation Definitions=true
 *	Add parenthesis for readability=true
 *	Allow Limit Service for Assignment Limitation=true
 *	Arithmetic Service Set=rb-services
 *	Auto-inline private methods (Smaller code-size - may be changed locally)=false
 *	Code Generator=Object Based Controller Implementation
 *	Common Subexpression Elimination=true
 *	Compiler=ME17 (dummy compiler)
 *	Constant Folding on Arithmetic Operations=true
 *	Constant Folding on Control Flow=true
 *	Constant Folding on Logical Operations=true
 *	Force Parenthesis for Binary Logical Operators=true
 *	Generate Access Macros for=()
 *	Generate Define Directives for Enum Values=true
 *	Generate Map File=false
 *	Generate OS Configuration=false
 *	Generate well-formed switch=true
 *	Hierarchical Code-Generation (may be changed locally)=false
 *	Initialise history variable with zero=true
 *	Inline directive=INLINE_FUNCTION
 *	Maximum bit Length (float)=32
 *	Maximum bit Length (int)=32
 *	Operating System=ERCOSEK
 *	Operator Simplification (general)=true
 *	Operator Simplification with Respect to Intervals=true
 *	Optimize Static Actions (Restricted Modelling)=false
 *	Outline Generated Methods (may be changed locally)=false
 *	Private directive=
 *	Public directive=
 *	Result on Division by Zero=numerator
 *	Target=Generic:ME17 with class support
 *	Use power of 2 approximations of literals=false
 *	Use SHIFT Operation on Signed Values instead of MUL Operation=true
 **************************************************************************
</RBHead>*/

#define BGBBAM_ModId            /* module identifier */

/* Include Header files	
 * ==================== */

#define  ASCET_HEADER_FLAG

#include SYSTEM_H               /* project specific header file     */
#include DFPMDEF_H              /* methods of fault path management */

/* DAMOS definitions and declarations */

#include <BGBBAM.d>

/* ASCET definitions and declarations */

#include <ascet_header.h>

/* Component specific definitions and declarations */

/* process prototypes for BGBBAM_IMPL */
void BGBBAM_10ms(void);

/* begin of code for BGBBAM_IMPL */

#define START_SECTION_Task_r10ms
#include "pragma.h"

void BGBBAM_10ms(void)
{
    bit _b_lam;
    uint8 _t1uint8;
    uint8 _t2uint8;

#if (SY_LSFVVK > 0)
    (_t1uint8 = usvk_w < USVKBR);
#else
    (_t1uint8 = true);
#endif
#if (SY_STETLR > 0)
    (_t2uint8 = lamsoni_w > LAMSBRW);
#else
    (_t2uint8 = true);
#endif
    /* _10ms: sequence call #2  */
    (_b_lam = ((GETBIT_UNSIGNED_U8_getBit((uint8)0, CWBGBBAM)) ? (GET_B_nmot && GET_B_sbbvk && _t1uint8 && _t2uint8) : true));
    /* _10ms: sequence call #3  */
    EDGEFALLING_U8_compute(&B_br2k_EFBAM, (uint8)GET_B_br2k);
    /* _10ms: sequence call #4  */
    if ((EDGEFALLING_U8_out(&B_br2k_EFBAM)) && _b_lam)
    {
        /* If-block: sequence call #4/Then #1  */
        TIMERRETRIGGER_U16_start(&B_mlbrf_TR, TMLBRF);
    }
    else
    {
        /* If-block: sequence call #4/Else #1  */
        TIMERRETRIGGER_U16_compute(&B_mlbrf_TR);
    }                           /* end if */
    /* _10ms: sequence call #5  */
    PUT_B_mlbrf(TIMERRETRIGGER_U16_out(&B_mlbrf_TR));
    /* _10ms: sequence call #6  */
    EDGERISING_U8_compute(&B_br2k_ERRAM, GET_B_br2k);
    /* _10ms: sequence call #7  */
    if (_b_lam && (EDGERISING_U8_out(&B_br2k_ERRAM)))
    {
        /* If-block: sequence call #7/Then #1  */
        TIMERRETRIGGER_U16_start(&B_mlbrr_TR, TMLBRR);
    }
    else
    {
        /* If-block: sequence call #7/Else #1  */
        TIMERRETRIGGER_U16_compute(&B_mlbrr_TR);
    }                           /* end if */
    /* _10ms: sequence call #8  */
    PUT_B_mlbrr(TIMERRETRIGGER_U16_out(&B_mlbrr_TR));
    /* _10ms: sequence call #9  */
    /* assignment to pspobr_w_ua: min=0, max=65535, hex=32768phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
    (pspobr_w_ua = Div_limit_u32u16_u16((uint32)ps_w << 15, pu_w));
    /* _10ms: sequence call #10  */
    /* assignment to fafbr_w_ua: min=0, max=65535, hex=32768phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
    (fafbr_w_ua = KLAFBR(pspobr_w_ua));
    /* _10ms: sequence call #11  */
    /* assignment to fafbr_w_temp: min=0, max=65535, hex=32768phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
    (fafbr_w_temp = MulShRight_limit_u16u16_u16(ftvdk_w, fho_w, 14));
    /* _10ms: sequence call #12  */
    /* assignment to ftabr_w_ua: min=0, max=65535, hex=32768phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
    (ftabr_w_ua = MulShRight_limit_u16u16_u16(fafbr_w_ua, fafbr_w_temp, 15));
    /* _10ms: sequence call #13  */
    if (!GET_B_nmot)
    {
        /* If-block: sequence call #13/Then #1  */
        /* assignment to mlbr_ua: min=0, max=65535, hex=10phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
        (mlbr_ua = (uint16)0);
    }
    else
    {
        /* If-block: sequence call #13/Else #1  */
        if (GET_B_mlbrf)
        {
            /* If-block: sequence call #13/Else #1/Then #1  */
            /* assignment to mlbr_ua: min=0, max=65535, hex=10phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
            (mlbr_ua = MulShRight_limit_u16u16_u16(MLBRF, ftabr_w_ua, 15));
        }
        else
        {
            /* If-block: sequence call #13/Else #1/Else #1  */
            if (GET_B_mlbrr)
            {
                /* If-block: sequence call #13/Else #1/Else #1/Then #1  */
                /* assignment to mlbr_ua: min=0, max=65535, hex=10phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
                (mlbr_ua = MulShRight_limit_u16u16_u16(MLBRR, ftabr_w_ua, 15));
            }
            else
            {
                /* If-block: sequence call #13/Else #1/Else #1/Else #1  */
                /* assignment to mlbr_ua: min=0, max=65535, hex=10phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
                (mlbr_ua = (uint16)0);
            }                   /* end if */
        }                       /* end if */
    }                           /* end if */
}

#define STOP_SECTION_Task_r10ms
#include "pragma.h"

/* end of code for BGBBAM_IMPL */

/**** test used systemconstants ****/
#ifndef SY_LSFVVK
#error >>>> 'SY_LSFVVK' undefined!
#endif
#ifndef SY_STETLR
#error >>>> 'SY_STETLR' undefined!
#endif
